"""init

Revision ID: 600d374265dc
Revises: 
Create Date: 2025-03-31 20:41:13.301904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600d374265dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_url', sa.String(), nullable=False),
    sa.Column('short_code', sa.String(), nullable=False),
    sa.Column('create_dt', sa.TIMESTAMP(), nullable=False),
    sa.Column('expire_dt', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_queried_dt', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('num_queries', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    # ### end Alembic commands ###
